### PR TITLE
Add nl.wikinews

### PR DESCRIPTION
**Pull request by revi**
Here's the PR, as I said in the email I prefer to commit from local, push to VCS, then pull from the server and run it there. Here's the PR as such.

### CODE REVIEW

**Comment by revi** [comment]
To make a local account (thus grant the botflag) I applied the patch manually and ran `sh local/bin/run_nlwn.sh` but I assume Pywikibot is not up to date and it's thinking nlwikinews is closed or Pywikibot is not told about nlwikinews' resurrection and configured to kill the connection.

```
tools.archiving@tools-bastion-03:~$ sh local/bin/run_nlwn.sh 
Traceback (most recent call last):
  File "/data/project/archiving/pkgsrc/core/pwb.py", line 255, in <module>
    if not main():
  File "/data/project/archiving/pkgsrc/core/pwb.py", line 249, in main
    run_python_file(filename, [filename] + args, argvu, file_package)
  File "/data/project/archiving/pkgsrc/core/pwb.py", line 121, in run_python_file
    main_mod.__dict__)
  File "/data/project/archiving/pkgsrc/core/scripts/archivebot.py", line 751, in <module>
    main()
  File "/data/project/archiving/pkgsrc/core/scripts/archivebot.py", line 721, in main
    a = pywikibot.Page(site, a, ns=10).title()
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/tools/__init__.py", line 1447, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/page.py", line 287, in title
    title = self._link.canonical_title()
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/page.py", line 5217, in canonical_title
    return "%s:%s" % (self.site.namespace(self.namespace),
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/site.py", line 904, in __getattr__
    % (self.__class__.__name__, attr))
AttributeError: RemovedSite instance has no attribute 'namespace'
<type 'exceptions.AttributeError'>
CRITICAL: Closing network session.
Command exited with non-zero status 1
0.87user 0.53system 0:06.52elapsed 21%CPU (0avgtext+0avgdata 26788maxresident)k
3800inputs+16outputs (1major+17438minor)pagefaults 0swaps
tools.archiving@tools-bastion-03:~$ 
```

**Comment by revi** [comment]
nlwikinews was removed from Closed wiki list as of wikimedia/pywikibot-core@a4813915b22affcd65800f492bfa7fa3a87eca70, and we are at wikimedia/pywikibot-core@f86235acd4266946ff01e47ae3d774f044eb4506, so we need to update the subprojects too.

**Comment by whym** [comment]
Since you have shell access to the Tool project, why not add your GitHub fork using 'git remote add' there and pull it by yourself? I can sync this repo with the live repo later.

(I have no problem with merging this, but I thought the above workflow might be easier for you to work with.)

About updating pywikibot: feel free to do so, but please test running the bot manually to see if there is unexpected failures, ideally for all wikis we are working for. Such failures occasionally happen with pywikibot's master, and that is why I don't use the latest master directly.

**Comment by revi** [comment]
```
tools.archiving@tools-bastion-03:~$ sh local/bin/run_nlwn.sh 
WARNING: API error mwoauth-invalid-authorization-invalid-user: The authorization headers in your request are for a user that does not exist here
Traceback (most recent call last):
  File "/data/project/archiving/pkgsrc/core/pwb.py", line 264, in <module>
    if not main():
  File "/data/project/archiving/pkgsrc/core/pwb.py", line 257, in main
    run_python_file(filename, [filename] + args, argvu, file_package)
  File "/data/project/archiving/pkgsrc/core/pwb.py", line 121, in run_python_file
    main_mod.__dict__)
  File "/data/project/archiving/pkgsrc/core/scripts/archivebot.py", line 815, in <module>
    main()
  File "/data/project/archiving/pkgsrc/core/scripts/archivebot.py", line 784, in main
    a = pywikibot.Page(site, a, ns=10).title()
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/tools/__init__.py", line 1474, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/page.py", line 2247, in __init__
    super(Page, self).__init__(source, title, ns)
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/page.py", line 204, in __init__
    self._link = Link(title, source=source, defaultNamespace=ns)
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/page.py", line 5365, in __init__
    self._defaultns = self._source.namespaces[defaultNamespace]
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/site.py", line 1018, in namespaces
    self._namespaces = NamespacesDict(self._build_namespaces())
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/site.py", line 2625, in _build_namespaces
    is_mw114 = MediaWikiVersion(self.version()) >= MediaWikiVersion('1.14')
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/site.py", line 2739, in version
    expiry=1).split(' ')[1]
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/site.py", line 1681, in get
    preloaded = self._get_general(key, expiry)
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/site.py", line 1627, in _get_general
    default_info = self._get_siteinfo(props, expiry)
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/site.py", line 1552, in _get_siteinfo
    data = request.submit()
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/data/api.py", line 2350, in submit
    self._data = super(CachedRequest, self).submit()
  File "/mnt/nfs/labstore-secondary-tools-project/archiving/pkgsrc/core/pywikibot/data/api.py", line 2180, in submit
    % (self.site, info))
pywikibot.exceptions.NoUsername: Failed OAuth authentication for wikinews:nl: The authorization headers in your request are for a user that does not exist here
<class 'pywikibot.exceptions.NoUsername'>
CRITICAL: Closing network session.
Command exited with non-zero status 1
1.90user 0.84system 0:07.40elapsed 37%CPU (0avgtext+0avgdata 34404maxresident)k
416inputs+3144outputs (0major+26519minor)pagefaults 0swaps
```
Checked out wikimedia/pywikibot@beccef37659928f7c0594ab7343656268366ff22.

All run_*.sh scripts run fine except nlwn. I think you'll need to make a local account? Seems OAuth can't do it.

**Comment by whym** [comment]
> All run_*.sh scripts run fine except nlwn. I think you'll need to make a local account? Seems OAuth can't do it.

Done! Apparently Pywikibot does not support auto-creation of local accounts from a SUL account, OAuth or not, so I manually did it.

See also https://phabricator.wikimedia.org/T183466

**Comment by revi** [comment]
```
tools.archiving@tools-bastion-03:~$ git checkout nlwikinews
M       pkgsrc/core
Switched to branch 'nlwikinews'
Your branch is up-to-date with 'revi/nlwikinews'.
tools.archiving@tools-bastion-03:~$ sh local/ls
sh: 0: Can't open local/ls
tools.archiving@tools-bastion-03:~$ sh local/bin/run_nlwn.sh 
Fetching template transclusions...
0.62user 0.31system 0:02.85elapsed 32%CPU (0avgtext+0avgdata 32116maxresident)k
0inputs+216outputs (0major+19454minor)pagefaults 0swaps
tools.archiving@tools-bastion-03:~$ 
```

Tested on new master, works fine. (It has no transclusion as of now, so it's natural there's nothing to do)

**Pull request merged**
